COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/panel_bd'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/panel_bd'
